apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argo-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: ambassador
    argocd.argoproj.io/sync-options: Validate=false
spec:
  rules:
    - http:
        paths:
          - path: "/argo/"
            backend:
              serviceName: argocd-server
              servicePort: 443