apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: demo-flamescope
    meta.helm.sh/release-namespace: default
  labels:
    app: {{.Values.name}}
    app.kubernetes.io/managed-by: Helm
  name: {{.Values.name}}
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{.Values.name}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - image: prakashramesh/{{.Values.name}}
        imagePullPolicy: Always
        name: {{.Values.name}}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /profiles
          name: profilevolume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /files
          type: ""
        name: profilevolume
