apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: {{.Values.name}}
  name: {{.Values.name}}
  namespace: app-ns
spec:
  progressDeadlineSeconds: 600
  replicas: {{.Values.deployment.replica}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - image: prakashramesh/{{.Values.name}}
        imagePullPolicy: Always
        name: {{.Values.name}}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /profiles
          name: profilevolume
        readinessProbe:
          httpGet:
            path: /profile
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /profile
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /files
          type: ""
        name: profilevolume
