apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: ambassador
    argocd.argoproj.io/sync-options: Validate=false
spec:
  rules:
    - http:
        paths:
          - path: "/"
            backend:
              serviceName: flamescope-service
              servicePort: 5000