apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-service
  namespace: app-ns
spec:
  selector:
    app: {{.Values.name}}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
